### ISSUE TITLE
UserAvatar cannot be rendered inside of new_follower ActivityItems

### ISSUE THREAD

**Issue by Monstergamester** [micahlt/offsides#13] opened 2024-06-01 20:09 UTC
Whenever I try to view my profile it just brings me to this screen when it loads 
![Screenshot_20240601_160919_Offsides](https://github.com/micahlt/offsides/assets/64338187/4c869881-87c7-44c5-8558-ee5fb232e58a)

**Comment by Monstergamester** [comment] 2024-06-02 01:22
Its now just loading my profile and then crashing. Still not sure how to fix

**Comment by micahlt** [comment] 2024-06-02 18:59
Would you be willing to take a screen recording of the issue for me?  I'd love to get this working for you.  Thanks!

**Comment by micahlt** [comment] 2024-06-04 16:49
Following up on this, is this still happening for you?

**Comment by Monstergamester** [comment] 2024-06-05 02:37
Oh sorry I didnt see this. The issue somehow fixed itself Im not sure how though.

**Comment by Monstergamester** [comment] 2024-06-10 22:16
Its happening again, but Im not sure how long it'll last this time. I'll make sure to keep you updated

**Comment by micahlt** [comment] 2024-06-11 14:06
If you are able to take a screen recording of the issue that would be amazing!

**Comment by Monstergamester** [comment] 2024-06-11 14:33
Here I've got one now

Uploading Screen_Recording_20240611_103231_Offsides.mp4…

**Comment by micahlt** [comment] 2024-06-11 14:34
Looks like you didn't let it upload all the way 😄

**Comment by Monstergamester** [comment] 2024-06-11 14:35
Oh sorry I dont use github a lot thanks for letting me know 


https://github.com/micahlt/offsides/assets/64338187/9c5fa7f9-ac3b-4ae1-a44c-b18a983dc6dc

**Comment by micahlt** [comment] 2024-06-11 14:45
> Oh sorry I dont use github a lot thanks for letting me know

No problem!  Thanks for the screen recording, I'll take a look and see if I can get a fix out for you :)

**Comment by Monstergamester** [comment] 2024-06-12 14:23
Its now just crashing whenever I click on my profile


https://github.com/micahlt/offsides/assets/64338187/75ada616-19f8-4325-9038-6bc827f455e5

**Comment by micahlt** [comment] 2024-06-13 17:16
Okay, would you please download the [latest release](https://github.com/micahlt/offsides/releases/download/0.6.8/offsides-0-6-8.apk) and try that?  I tried to implement some better error handling for the profile page.

**Comment by Monstergamester** [comment] 2024-06-13 17:23
Hmmm that didnt seem to work. Its still crashing. Im starting to think it may be an error with my phone 


https://github.com/micahlt/offsides/assets/64338187/782cd637-257b-46e6-a834-7165a705fb46

**Comment by micahlt** [comment] 2024-06-13 19:15
I released another version!  Please try it [here](https://github.com/micahlt/offsides/releases/download/0.6.10/offsides-0-6-10.apk).  This version should report any errors directly to me so I can look at the stack trace and debug it myself.

**Comment by micahlt** [comment] 2024-06-13 19:18
Okay, I got the logs!  I'll let you know as soon as I have a fix.

**Comment by Monstergamester** [comment] 2024-06-13 19:18
Yep I just downloaded it. Should I keep repeating the crash so that it reports to you?

**Comment by Monstergamester** [comment] 2024-06-13 19:18
Thank you so much :)

**Comment by micahlt** [comment] 2024-06-13 19:56
Okay, give the latest update a shot!

**Comment by Monstergamester** [comment] 2024-06-13 20:00
YOOOO THANK YOU SO MUCH IT WORKED

**Comment by micahlt** [comment] 2024-06-13 20:03
Wonderful!  

For my own reference: This is caused by the fact that I'm trying to render a `UserAvatar` component in an `ActivityItem` of type `new_follower`.  Until we know what the `new_follower` schema looks like, we cannot render that component without a crash.

**Comment by Monstergamester** [comment] 2024-06-13 20:09
Hopefully you can get replying to replies and image uploading working soon because Im loving the app otherwise

**Comment by micahlt** [comment] 2024-06-13 20:11
Yep!  The issue is that I don't own an iPhone to reverse engineer the API, so the only time I can really figure out new features is when I see my girlfriend who _does_  have an iPhone.  Next time I see her I'll get as much endpoint data as I can to implement those features :)

Polls are also coming soon!

**Comment by micahlt** [comment] 2024-12-23 03:28
@Monstergamester by the way, I got replying to replies and image uploading both working fine!

**Comment by micahlt** [comment] 2024-12-23 03:28
Closing this for now since it doesn't affect daily usage.

**Comment by micahlt** [comment] 2024-12-23 03:29
Closing this for now since it doesn't affect daily usage.

**Closed by micahlt** 2024-12-23 03:28 UTC
Labels: bug, needs API
