### ISSUE TITLE
New User Verification Error

### ISSUE THREAD

**Issue by Xoldrife** [micahlt/offsides#34] opened 2024-11-29 01:04 UTC
I'm a new user of Offsides and did the phone number verification, however when I had the email sent to my student account and I clicked the link, it told me I was verified, but the app wouldn't reflect that. The first picture is what would happen after I tried to continue. The second picture is what loaded when I closed the app and reopened it.
![Screenshot_20241128_185615_Offsides](https://github.com/user-attachments/assets/f3e43c52-9773-42e9-8437-fc5e326f9c1f)
![Screenshot_20241128_185645_Offsides](https://github.com/user-attachments/assets/b7db2aa0-4acb-4f38-8fc7-fa000b8c68fa)

**Comment by micahlt** [comment] 2024-12-04 17:37
Interesting.  That's odd.  I'll take a look at the logs.

**Comment by micahlt** [comment] 2024-12-18 21:45
This is a duplicate of #26 and will be tracked there.

**Closed** 2024-12-18 21:45 UTC
