### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by RahilJiwani** [micahlt/offsides#38] opened 2024-12-28 19:37 UTC
0.7.8 caused the screen to be completely gray and nothing will load. Reverting to an older version did not fix my issue.

**Comment by micahlt** [comment] 2024-12-28 20:41
Please update to 0.7.9 and see if that resolves your issue.

**Comment by RahilJiwani** [comment] 2024-12-28 20:58
Updating to 0.7.9 didn't fix it unfortunately

**Comment by tails618** [comment] 2024-12-28 21:36
I just updated from 0.7.7 to 0.7.9 and I now have this issue.

**Comment by HauntedBunnies** [comment] 2024-12-28 21:43
Be sure to check the filter on your posts. I had the same issue but it was just because I hadn't selected whether to use "Top", "Hot", or "Recent".

**Comment by RahilJiwani** [comment] 2024-12-28 21:49
> Be sure to check the filter on your posts. I had the same issue but it was just because I hadn't selected whether to use "Top", "Hot", or "Recent".

No, I mean completely gray as in not even the banner at the top to select those will load.

**Comment by micahlt** [comment] 2024-12-28 21:58
Please uninstall Offsides completely, and then reinstall the latest version @RahilJiwani @tails618.  If it doesn't work after that please let me know.

**Comment by RahilJiwani** [comment] 2024-12-28 22:07
Didn't work

**Comment by micahlt** [comment] 2024-12-28 22:50
I just released a new version.  Please uninstall Offsides, then download 0.7.10, then install and try to log in.

**Comment by tails618** [comment] 2024-12-28 23:13
> Please uninstall Offsides completely, and then reinstall the latest version @RahilJiwani @tails618.  If it doesn't work after that please let me know.

For what it's worth this *did* work for me. I'll try uninstalling and installing v0.7.10 now.

**Comment by tails618** [comment] 2024-12-28 23:16
A fresh install of v0.7.10 worked as well.

**Comment by micahlt** [comment] 2024-12-28 23:33
> A fresh install of v0.7.10 worked as well.

Great, glad to hear it.  Just an FYI to anyone viewing this thread - the last three days of bugs have mostly been caused by Offsides migrating to a different internal database system that is up to 30x faster.  So while I'm aware that there have been multiple major issues, things should be stabilizing and you should notice Offsides being noticably faster than it has been in the past.

**Comment by RahilJiwani** [comment] 2024-12-29 00:42
I must be doing something wrong then. I tried uninstalling completely and reinstalling the 0.7.10 a few times but can't fix the issue

**Comment by micahlt** [comment] 2024-12-29 05:13
Okay, let me get some more details so I can track down the issue.  Can you provide me with your:

- Android version
- Phone model

**Comment by RahilJiwani** [comment] 2024-12-29 05:40
Android version 12, galaxy s10+

**Comment by micahlt** [comment] 2024-12-29 07:36
When you log in, does the app ask you to complete the email verification step?

**Comment by RahilJiwani** [comment] 2024-12-29 08:57
Yes it does

**Comment by micahlt** [comment] 2024-12-29 15:51
Okay - that is the issue.  Many users are experiencing an issue with logging in that I haven't been able to diagnose yet.  According to my crash logs, you are experiencing that issue.  For now I will close this issue in favor of #26 where current info about this problem is.  Please follow that issue for further updates.

**Closed** 2024-12-29 15:51 UTC
Labels: bug
